CREATE TABLE Employee
(
  ID INT NOT NULL,
  name VARCHAR(30) NOT NULL,
  address VARCHAR(30) NOT NULL,
  phone VARCHAR(11) NOT NULL,
  salary INT NOT NULL,
  bankDetail VARCHAR(20) NOT NULL,
  role VARCHAR(20) NOT NULL,
  Email VARCHAR(30) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE profEmp
(
  ID INT NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID) REFERENCES Employee(ID)
);

CREATE TABLE Resident
(
  ID INT NOT NULL,
  name VARCHAR(30) NOT NULL,
  phone VARCHAR(11) NOT NULL,
  Email VARCHAR(30) NOT NULL,
  mail VARCHAR(30) NOT NULL,
  address VARCHAR(30) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE polEmp
(
  party VARCHAR(20) NOT NULL,
  ID INT NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID) REFERENCES Employee(ID),
  FOREIGN KEY (ID) REFERENCES Resident(ID)
);

CREATE TABLE Member
(
  ID INT NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID) REFERENCES polEmp(ID)
);

CREATE TABLE Chairman
(
  ID INT NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID) REFERENCES polEmp(ID)
);

CREATE TABLE Budget
(
  year INT NOT NULL,
  PRIMARY KEY (year)
);

CREATE TABLE Source
(
  amount INT NOT NULL,
  sDate DATE NOT NULL,
  sID INT NOT NULL,
  year INT,
  PRIMARY KEY (sID),
  FOREIGN KEY (year) REFERENCES Budget(year)
);

CREATE TABLE Collection
(
  ID INT NOT NULL,
  sID INT NOT NULL,
  PRIMARY KEY (sID),
  FOREIGN KEY (sID) REFERENCES Source(sID)
);

CREATE TABLE GovFund
(
  sID INT NOT NULL,
  PRIMARY KEY (sID),
  FOREIGN KEY (sID) REFERENCES Source(sID)
);

CREATE TABLE Taxes
(
  type VARCHAR(10) NOT NULL,
  sID INT NOT NULL,
  PRIMARY KEY (sID),
  FOREIGN KEY (sID) REFERENCES Collection(sID)
);

CREATE TABLE Donor
(
  name VARCHAR(30) NOT NULL,
  ID INT NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE Inspector
(
  ID INT NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID) REFERENCES profEmp(ID)
);

CREATE TABLE Committee
(
  Name VARCHAR(30) NOT NULL,
  role VARCHAR(30) NOT NULL,
  ID INT NOT NULL,
  PRIMARY KEY (Name),
  FOREIGN KEY (ID) REFERENCES Chairman(ID)
);

CREATE TABLE Institution
(
  address VARCHAR(30) NOT NULL,
  instName VARCHAR(30) NOT NULL,
  type CHAR(10) NOT NULL,
  commitName VARCHAR(30) NOT NULL,
  PRIMARY KEY (address),
  FOREIGN KEY (commitName) REFERENCES Committee(Name)
);

CREATE TABLE Donation
(
  sID INT NOT NULL,
  dID INT NOT NULL,
  PRIMARY KEY (sID),
  FOREIGN KEY (sID) REFERENCES Source(sID),
  FOREIGN KEY (dID) REFERENCES Donor(ID)
);

CREATE TABLE Fines
(
  reason VARCHAR(40) NOT NULL,
  sID INT NOT NULL,
  iID INT NOT NULL,
  PRIMARY KEY (sID),
  FOREIGN KEY (iID) REFERENCES Inspector(ID),
  FOREIGN KEY (sID) REFERENCES Collection(sID)
);

CREATE TABLE Inquiries
(
  iID INT NOT NULL,
  iDate DATE NOT NULL,
  type VARCHAR(10) NOT NULL,
  details VARCHAR(50) NOT NULL,
  status CHAR(1) NOT NULL,
  ID INT NOT NULL,
  commitName VARCHAR(30) NOT NULL,
  PRIMARY KEY (iID),
  FOREIGN KEY (ID) REFERENCES Resident(ID),
  FOREIGN KEY (commitName) REFERENCES Committee(Name)
);

CREATE TABLE memberAt
(
  Name VARCHAR(30) NOT NULL,
  ID INT NOT NULL,
  PRIMARY KEY (Name, ID),
  FOREIGN KEY (Name) REFERENCES Committee(Name),
  FOREIGN KEY (ID) REFERENCES Member(ID)
);

CREATE TABLE Finance
(
  amount INT NOT NULL,
  year INT NOT NULL,
  Name VARCHAR(30) NOT NULL,
  PRIMARY KEY (year, Name),
  FOREIGN KEY (year) REFERENCES Budget(year),
  FOREIGN KEY (Name) REFERENCES Committee(Name)
);
