DELETE FROM Finance CASCADE;

DELETE FROM memberAt CASCADE;

DELETE FROM Inquiries CASCADE;

DELETE FROM Fines CASCADE;

DELETE FROM Donation CASCADE;

DELETE FROM Institution CASCADE;

DELETE FROM Committee CASCADE;

DELETE FROM Inspector CASCADE;

DELETE FROM Donor CASCADE;

DELETE FROM Taxes CASCADE;

DELETE FROM GovFund CASCADE;

DELETE FROM Collection CASCADE;

DELETE FROM Source CASCADE;

DELETE FROM Budget CASCADE;

DELETE FROM Chairman CASCADE;

DELETE FROM Member CASCADE;

DELETE FROM polEmp CASCADE;

DELETE FROM Resident CASCADE;

DELETE FROM profEmp CASCADE;

DELETE FROM Employee CASCADE;

commit;
