INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('9294 Arapahoe Center', 'ssZlddIGTl', 'clinic                                  ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('70 Nancy Avenue', 'VZisvLBJrZ', 'hospital                                ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('73 Packers Terrace', 'lgeucsjwws', 'Sports hall                             ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('5 Waywood Drive', 'RdIkDxWzjU', 'bank                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('3374 Macpherson Center', 'yUmFPeOXIb', 'park                                    ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('4 David Junction', 'pUrEQskEci', 'stadium                                 ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('6509 Cardinal Alley', 'oTCOfIwRtu', 'university                              ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('343 Prairieview Place', 'UmbksrGVxA', 'Sports hall                             ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('33 Sachs Plaza', 'JBtNuthGSL', 'Sports hall                             ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('3 Upham Lane', 'yniInhyAwS', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('95 Mitchell Pass', 'vGdnaXfnhp', 'mall                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('4565 Longview Alley', 'nvHcOYNwnG', 'park                                    ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('4855 Porter Point', 'CgZOtLkgVG', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('3 Mandrake Pass', 'UEcqsKhGGh', 'university                              ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('465 Forest Run Circle', 'MCacBTqcqC', 'stadium                                 ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('293 Pankratz Parkway', 'AVlxqPxJgn', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('0195 Crescent Oaks Street', 'HmqwnEMtQE', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('71 Killdeer Alley', 'HgaPRPWjUO', 'museum                                  ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('24 Weeping Birch Crossing', 'TajYWXKjfK', 'university                              ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('1 Glacier Hill Alley', 'QGjYLFCzcs', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('871 John Wall Trail', 'BbPIBxLYsR', 'school                                  ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('0209 Division Plaza', 'yfqNRSdVBA', 'park                                    ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('5339 Kipling Drive', 'aiAvDJDDet', 'bank                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('95751 Kingsford Lane', 'UXnhZjkYcl', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('18 Pine View Place', 'kMaUKVnPpt', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('616 Sheridan Trail', 'zTtSmAlqwP', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('31350 Judy Plaza', 'PXdqVsSblB', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('46 Moose Hill', 'GUBeyQnJgs', 'mall                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('55 Fordem Trail', 'SZzvGsmvVU', 'university                              ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('85178 Corry Crossing', 'ioOSovqDwN', 'school                                  ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('7 Merrick Trail', 'DaZAjiHKQO', 'school                                  ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('9708 Evergreen Court', 'BltRobAxBL', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('485 Debs Junction', 'GhsUebwFfr', 'park                                    ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('9603 Westerfield Pass', 'NBRvRvjRdR', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('3 Merrick Parkway', 'uPUXvRHCWV', 'clinic                                  ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('233 Acker Trail', 'DuxvKnflCM', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('163 Clove Park', 'CpqnEHcKkG', 'clinic                                  ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('45 Brown Junction', 'NMpfVriDFd', 'mall                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('48436 Chive Plaza', 'BSCMNilfCK', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('99 Vidon Court', 'SNcIILkbvL', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('74 Stone Corner Trail', 'oscsfvYRTK', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('43414 Merrick Center', 'xsLJsFXUNN', 'hospital                                ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('91 Crownhardt Crossing', 'nXLKOVycVi', 'park                                    ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('20770 Shopko Park', 'kIDPKqBirY', 'mall                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('55 Northview Avenue', 'AhDkHxhuTp', 'clinic                                  ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('238 Russell Alley', 'bVkdMlfatG', 'park                                    ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('46568 Sutteridge Alley', 'fgbDUoZupF', 'Sports hall                             ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('98 Express Pass', 'pdjQKCdhhY', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('26 Barnett Drive', 'oNQNkuRiGQ', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('523 Meadow Ridge Street', 'kAfxSTrLGl', 'Nature site                             ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('411 Swallow Circle', 'SeUHHufpoe', 'clinic                                  ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('6499 Prairie Rose Parkway', 'ShZObWVXVm', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('07 Lindbergh Circle', 'mDCIUKBCbJ', 'visitors Center                         ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('5525 Meadow Vale Road', 'oWXDfJJdzn', 'Sports hall                             ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('76317 Londonderry Point', 'jeOMWUGjdz', 'stadium                                 ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('8 Leroy Court', 'WpkXjDFIhe', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('6000 Golf Junction', 'VRDcvqEVtU', 'mall                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('92 Ridgeview Hill', 'tMhZhkvXMw', 'Sports hall                             ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('6 Prairieview Lane', 'YIzorvLHiu', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('36267 2nd Terrace', 'WhTuunZevs', 'stadium                                 ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('903 North Crossing', 'GGlfrljDNs', 'mall                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('1046 Ilene Court', 'DUyiSOqLyZ', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('6 Delladonna Park', 'FLHIxlzwSx', 'bank                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('19 Carberry Avenue', 'UcDvEWJQMb', 'museum                                  ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('219 Bowman Plaza', 'KFezdNGGcr', 'hospital                                ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('40816 Crest Line Junction', 'boDbVjRFHr', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('935 Manitowish Lane', 'cVBkqFrXTJ', 'university                              ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('59969 Sunfield Drive', 'UmErsjIwPJ', 'museum                                  ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('7 Dorton Center', 'wDyLIVUrWr', 'school                                  ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('972 Northfield Trail', 'YKOvNATHEB', 'university                              ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('1777 Bonner Crossing', 'tZjCrJZylY', 'bank                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('646 Meadow Valley Trail', 'RiSGtnUyka', 'community Center                        ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('0626 Warbler Hill', 'VqVrdTeBzA', 'museum                                  ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('60402 Superior Junction', 'YPdUhPLCYL', 'Sports hall                             ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('175 Dawn Terrace', 'pHtdURQSnI', 'mall                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('8861 Crescent Oaks Hill', 'pCxUCdfWuD', 'visitors Center                         ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('0 Kropf Place', 'RzqqFmUOhu', 'stadium                                 ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('7 Muir Pass', 'wlzWEjCykE', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('55 Sunnyside Parkway', 'PyUxCupYVF', 'synagogue                               ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('8923 Toban Point', 'wetKOhqXxw', 'mall                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('3 Spaight Street', 'HCBMzxzySR', 'community Center                        ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('5 Lindbergh Street', 'VIYzWTdcAO', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('1946 Blackbird Park', 'UGLbJjjlsQ', 'hospital                                ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('71 International Hill', 'PTvJZkXpkH', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('9048 Northridge Park', 'OsyWSMAEQH', 'school                                  ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('045 Randy Trail', 'QCeGuQEGQZ', 'park                                    ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('8 Dayton Center', 'kHqnhdrnBr', 'bank                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('3432 Graceland Park', 'icLyElOKFs', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('517 Golden Leaf Trail', 'OJLvFecJdp', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('18743 Longview Alley', 'oFGxKmLXWf', 'bank                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('6964 Cottonwood Place', 'daQMwxiooG', 'museum                                  ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('8873 Westend Circle', 'EGxjDUtZJj', 'university                              ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('7 Springview Drive', 'GdkWMYJlZm', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('90 Welch Park', 'iffdfMRJEU', 'school                                  ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('540 Pepper Wood Road', 'FYvcqOuwru', 'Sports hall                             ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('2057 Hintze Road', 'zoRGIHLsQL', 'bank                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('35 Pennsylvania Road', 'xzpVdjAGri', 'university                              ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('0 Messerschmidt Way', 'SeXtxvsehX', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('121 Birchwood Parkway', 'fMSykhIFYF', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('164 Bowman Park', 'BwnzWiwdsP', 'stadium                                 ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('2 Merry Trail', 'jyXyKWUQOn', 'school                                  ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('79 Pepper Wood Avenue', 'aBhKJdTwdx', 'school                                  ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('62 Sunnyside Plaza', 'WTbhUEebmo', 'mall                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('2 Ruskin Park', 'virYQxySSt', 'synagogue                               ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('785 Hallows Point', 'bZWODyJTuU', 'Sports hall                             ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('9245 Kedzie Hill', 'sbAjChFIun', 'museum                                  ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('15 4th Street', 'TRzjcQAwhl', 'museum                                  ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('457 Dayton Center', 'vRWipRqIMU', 'museum                                  ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('6 Mandrake Pass', 'wrcLxSCoev', 'Nature site                             ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('22 Towne Hill', 'kCeUlJhuaJ', 'Sports hall                             ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('44780 Ohio Avenue', 'hdzNCAtsLm', 'Sports hall                             ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('6580 Continental Parkway', 'rTDcYEMXoY', 'mall                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('7092 Ruskin Point', 'dpagObNqtm', 'community Center                        ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('1 Ridgeway Drive', 'AjKdUBWupR', 'museum                                  ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('0875 Miller Terrace', 'DEcgOHYpWM', 'Sports hall                             ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('0248 Victoria Place', 'WKXnbscihb', 'mall                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('811 Carberry Pass', 'MTZWdToyNN', 'museum                                  ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('30090 Springs Alley', 'mDgvCpJJSy', 'clinic                                  ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('17 Coolidge Hill', 'PeIoAmdMEH', 'park                                    ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('8197 Ryan Hill', 'BJBWaDDWgA', 'community Center                        ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('5 Lyons Alley', 'lzrkbleedM', 'mall                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('5 Barby Lane', 'OLmhxBvTRG', 'university                              ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('963 Karstens Drive', 'GOCxQXCRpp', 'school                                  ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('2 Graceland Circle', 'ijmDcPUgcb', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('3 Pennsylvania Plaza', 'vJmEOircvB', 'school                                  ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('08 Karstens Terrace', 'FOQYeOVRsf', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('3 Bonner Parkway', 'GYvVExXQPA', 'hospital                                ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('5581 Texas Center', 'HeKCxHJKCq', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('6 Morning Lane', 'IlokMkeLiQ', 'school                                  ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('5 Lukken Hill', 'KartLrAbdT', 'visitors Center                         ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('83 John Wall Way', 'VYIQdlneKA', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('13892 Corben Road', 'NKzBJIkeuf', 'Sports hall                             ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('9491 Hermina Crossing', 'fuIRzNHWtm', 'bank                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('25611 Lunder Circle', 'YUcmLedVZH', 'synagogue                               ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('426 7th Park', 'SwYydiAtWc', 'synagogue                               ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('74269 Goodland Crossing', 'nGokUkqUGT', 'clinic                                  ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('32 Melrose Place', 'Gwmrkfpldk', 'clinic                                  ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('8453 Pepper Wood Court', 'dBpVqssiJv', 'university                              ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('1 Utah Crossing', 'LTLZnwrDGn', 'university                              ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('78388 David Lane', 'PgHmMFJKBQ', 'school                                  ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('6 Continental Plaza', 'kkQjruBEAz', 'Sports hall                             ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('12969 Division Court', 'FcKVtrmUjX', 'school                                  ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('000 Cardinal Place', 'DkiKTARkKn', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('95747 Charing Cross Lane', 'YIJxRlnJsT', 'university                              ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('252 Talisman Street', 'VqAiSmPvFX', 'synagogue                               ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('949 Brickson Park Drive', 'pSWMtFvuff', 'community Center                        ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('70558 Sage Court', 'lQuJDFElUa', 'community Center                        ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('533 South Place', 'RaOyqEAEgV', 'clinic                                  ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('226 Darwin Park', 'vXDaPzYWSU', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('803 Nelson Way', 'ywjTMoBZia', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('8 Almo Circle', 'qqaHppgEBg', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('3 Bunting Lane', 'SShIUeVeBK', 'park                                    ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('425 Calypso Terrace', 'BKQbIjFesI', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('174 Meadow Valley Street', 'hImRFFsuOM', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('17 Burning Wood Street', 'rzUkKQAJOk', 'Sports hall                             ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('22107 Menomonie Circle', 'JdzSLLYDKP', 'clinic                                  ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('065 Surrey Terrace', 'AmMdpPcSjI', 'Sports hall                             ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('4 Heath Place', 'dmafcEGcEv', 'university                              ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('85986 Myrtle Lane', 'rxrDCgxGzI', 'synagogue                               ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('23 Mesta Junction', 'MtniiyrLJF', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('2090 Menomonie Court', 'DaKIdtEbLl', 'mall                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('8 Ruskin Junction', 'ExLaZRNZim', 'synagogue                               ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('70 Gale Point', 'aHMvNRycHn', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('0057 Dryden Plaza', 'axTJhTwMqA', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('04 Goodland Junction', 'EPhOLvIyEy', 'museum                                  ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('54337 Crowley Alley', 'XreZgzjuzK', 'university                              ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('140 Thackeray Lane', 'IYKNAFCZTx', 'stadium                                 ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('065 Artisan Park', 'rNggMauAbh', 'bank                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('2 Springview Plaza', 'PlROomFtAp', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('672 Del Mar Street', 'vHbJoKouBS', 'visitors Center                         ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('4942 Waywood Avenue', 'WBSCaLMZVj', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('8 Saint Paul Parkway', 'HkAGpYkYrw', 'bank                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('2669 Melby Way', 'kUkpfXdeCI', 'mall                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('34 Memorial Drive', 'dTsDxULeLx', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('3710 Elka Terrace', 'lhqIoVuXtm', 'mall                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('536 6th Avenue', 'NDPOyktpAv', 'mall                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('015 Anniversary Drive', 'LGmSjcbfKF', 'Nature site                             ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('4 Express Alley', 'cNgnbMHrgZ', 'Sports hall                             ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('55942 Gulseth Hill', 'BzlIpXBued', 'bank                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('68 1st Center', 'JBFYhVnmqs', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('1502 Banding Road', 'WvBAaWgfJj', 'park                                    ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('8718 Hollow Ridge Park', 'LPLOouXQAH', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('3 Monument Point', 'QTsxuupQoR', 'bank                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('20 Schmedeman Plaza', 'rxkEZsieYv', 'museum                                  ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('057 Mosinee Pass', 'naxsSSiQPf', 'school                                  ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('0 Thierer Hill', 'XxPTuSsDxZ', 'university                              ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('15 Vernon Center', 'QwALSpqfwE', 'park                                    ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('59 Dakota Junction', 'rUtbLPGrbp', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('588 Kensington Place', 'rTopmLyQOW', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('947 Sage Circle', 'yadXRkhhGh', 'university                              ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('03146 Ludington Terrace', 'dAlZTqqllc', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('4778 Meadow Vale Drive', 'DxXFHRFZVo', 'visitors Center                         ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('6355 Basil Parkway', 'ZVfDGZhBIb', 'mall                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('280 Loomis Lane', 'BNqqoWNmyC', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('82 Helena Alley', 'DWmPDLAQmV', 'bank                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('8815 Anhalt Court', 'SGCRwbAZFK', 'school                                  ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('84 Muir Pass', 'NDjpgesECH', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('6 Fisk Drive', 'ijopzukpmL', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('251 Spenser Drive', 'ffWgNIDewp', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('918 Monument Hill', 'ewdqIMDHAV', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('921 Porter Lane', 'xKeStQgPJL', 'school                                  ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('308 Roth Center', 'kpYdUGmjfa', 'visitors Center                         ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('73259 Scofield Crossing', 'LMyLljArHT', 'clinic                                  ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('789 Bunting Junction', 'rFtBEKxmcj', 'hospital                                ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('0 Havey Park', 'CxyupRaMuS', 'hospital                                ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('41 Novick Junction', 'IvyyDxfBOD', 'mall                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('9164 Briar Crest Alley', 'gFtXpeyABi', 'synagogue                               ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('12 Vahlen Plaza', 'kzaFfORthu', 'university                              ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('209 Vidon Park', 'EBCPvnBoYi', 'hospital                                ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('59582 American Trail', 'phtYISddPB', 'bank                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('81137 Morningstar Terrace', 'ilPSfmznXS', 'school                                  ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('2543 Merchant Parkway', 'mVZvcYEtni', 'community Center                        ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('4 Starling Way', 'XuoHLdSGYk', 'clinic                                  ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('395 Sauthoff Junction', 'zJLipzGhIv', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('74 Claremont Road', 'eQYMLjLQGA', 'museum                                  ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('4565 Sunfield Hill', 'QikERaXOBA', 'visitors Center                         ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('248 Lukken Drive', 'ufBlEHtipJ', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('72222 South Crossing', 'JOAiLMcwRR', 'community Center                        ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('7 Eggendart Street', 'GQGqbbDPNS', 'mall                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('0 Blaine Place', 'IPwpAlvcEu', 'Sports hall                             ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('35 Huxley Lane', 'BbkrtjBjtL', 'school                                  ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('651 Northport Crossing', 'FdzzPqETJY', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('8300 Village Green Court', 'KKAMdhPTxn', 'school                                  ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('529 Old Shore Park', 'NfYfgdtODt', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('49 Old Shore Parkway', 'wVLASXrXWO', 'school                                  ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('2525 Mandrake Circle', 'NnCCqugSbv', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('031 Surrey Lane', 'pmQaiunKLL', 'school                                  ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('986 Morrow Hill', 'jUxNIFRKYU', 'hospital                                ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('87496 Mesta Trail', 'rwZWGcktTB', 'stadium                                 ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('32 Anzinger Place', 'fqVBSwJfnm', 'mall                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('2 Waxwing Road', 'YBtehabKOb', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('22174 Canary Point', 'baQmgYMEke', 'mall                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('77907 Monterey Drive', 'NBcTEeblxO', 'bank                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('6096 Bartelt Park', 'mVjeZRsvZX', 'clinic                                  ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('50 Stone Corner Way', 'WSIUckcKfl', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('1837 Hazelcrest Point', 'urUKlgihLL', 'visitors Center                         ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('897 Goodland Center', 'fxyEUUnrXk', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('91459 Anniversary Pass', 'nVbnOwIHUn', 'school                                  ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('988 Emmet Park', 'lrGUyvhHct', 'school                                  ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('695 Derek Street', 'xVMmpQmAyX', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('9019 Brown Lane', 'fCORNWKIcr', 'mall                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('023 Aberg Place', 'SvLJNRMBIW', 'visitors Center                         ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('7 Thackeray Trail', 'ekAuuAHnNA', 'mall                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('430 Superior Road', 'lWBsKGZIWS', 'bank                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('747 Cottonwood Street', 'edBoneWxpA', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('72 Donald Plaza', 'iENhNeoaVX', 'hospital                                ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('7932 Dahle Park', 'NyXMrXhKxl', 'school                                  ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('68576 7th Parkway', 'oIXsxhkjLn', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('8 Delaware Court', 'cNsjLLDTCl', 'visitors Center                         ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('95875 Center Street', 'FhHJnYrZCh', 'mall                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('7877 Butterfield Court', 'qYXqPXafDN', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('207 Debra Alley', 'REikRMBBpr', 'mall                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('35 Monica Crossing', 'tOmurkFaJf', 'mall                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('23 Kropf Park', 'xdNhGZWlnl', 'hospital                                ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('044 Tomscot Drive', 'wdFtLWLYOQ', 'university                              ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('7 Oriole Crossing', 'ClqYjLgsYa', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('8549 Kim Parkway', 'TnakYakXPZ', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('04 Stone Corner Terrace', 'PvBRZOCOMc', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('88 Columbus Plaza', 'wXKmOWSgJD', 'community Center                        ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('4 Comanche Circle', 'nigWREjcXQ', 'Nature site                             ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('0074 Bayside Circle', 'JFkfnkDGcm', 'clinic                                  ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('7585 Judy Place', 'sWkigoOhBY', 'clinic                                  ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('761 Hooker Point', 'gjoNTIXvnQ', 'stadium                                 ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('84372 Express Plaza', 'oGZeYrqYYh', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('33 Arkansas Circle', 'CNtetHkdRy', 'mall                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('2197 Farwell Trail', 'ULyAlVddYj', 'mall                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('1 Carioca Crossing', 'EdATUgEFaW', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('52 Barnett Park', 'jzNPeJDopF', 'bank                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('552 Northwestern Park', 'wMRYaTctrQ', 'university                              ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('1155 Dottie Park', 'BQxDWBewJG', 'mall                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('4 Jay Plaza', 'GTCkdXCqbv', 'Nature site                             ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('2815 Miller Parkway', 'qgQScfMxvO', 'community Center                        ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('2986 Basil Pass', 'UqQTvyAkGJ', 'mall                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('084 Hudson Court', 'kgCOemXguw', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('0074 Talmadge Trail', 'zLwEDwmaBZ', 'bank                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('95796 Acker Lane', 'xqmDqLaqGU', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('6 Thierer Lane', 'HkdGtOWSxf', 'mall                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('2332 Jay Court', 'TjMxbEzUIW', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('51444 Eggendart Avenue', 'aZVmmXhfVc', 'hospital                                ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('58 Arapahoe Road', 'fXyGhdZzVD', 'visitors Center                         ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('83797 Truax Court', 'htPfWuNhBp', 'stadium                                 ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('7 Warrior Park', 'BQedlkWpwd', 'community Center                        ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('73066 Autumn Leaf Trail', 'PnhmZENAGv', 'school                                  ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('3 Cardinal Place', 'qtcVQuuFDr', 'Sports hall                             ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('11965 Holy Cross Point', 'fXMkYcjcle', 'stadium                                 ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('61 Cascade Terrace', 'XSUFlhdgVv', 'community Center                        ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('7 Sullivan Crossing', 'knCWnkEFfX', 'mall                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('237 Carberry Lane', 'jpBlNlgVlM', 'stadium                                 ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('166 Shasta Parkway', 'pcxaZBmbkq', 'hospital                                ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('4 Sunnyside Road', 'WBFyEBYUBu', 'visitors Center                         ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('3 Novick Street', 'IcDmBBSHED', 'hospital                                ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('468 Clyde Gallagher Pass', 'guXoVsUaCJ', 'school                                  ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('6404 Russell Hill', 'PYFJJrYyzk', 'clinic                                  ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('8 Scofield Parkway', 'FNkWuCOfZj', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('26705 Scofield Street', 'FUzOZRqLSb', 'university                              ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('8 Harper Parkway', 'OLPEaGvaLp', 'mall                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('79070 Lerdahl Avenue', 'XdQKYbSwHT', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('4 Northfield Park', 'LKjjmxLDty', 'mall                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('180 Thompson Park', 'kWuhaZguGW', 'Nature site                             ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('676 Sloan Point', 'zZhNoFDLUs', 'synagogue                               ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('667 7th Lane', 'ywfGNGTvrV', 'stadium                                 ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('53 Barnett Lane', 'WQnFHaDnim', 'museum                                  ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('26553 Sage Parkway', 'XkxGgubObw', 'hospital                                ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('168 Evergreen Way', 'wSGHWOQvGQ', 'university                              ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('77 Village Green Trail', 'hGyyLDLnvk', 'community Center                        ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('7920 Derek Lane', 'fAeYtnEBxl', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('6 Mallard Junction', 'zASJxqJXGC', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('28436 Forest Run Pass', 'buhLWYQTgv', 'clinic                                  ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('4868 Sunnyside Court', 'qatEXXGhrG', 'park                                    ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('0 Straubel Place', 'WmfAjKbUSe', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('2 Holy Cross Drive', 'IKKheAXLAh', 'school                                  ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('0788 Arizona Lane', 'OTDEkWqlSt', 'bank                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('0430 Drewry Center', 'TtCDuqMwcO', 'community Center                        ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('839 Forster Terrace', 'NtdqXFOuXq', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('06358 Summit Circle', 'IOLHnHMJzl', 'Sports hall                             ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('7326 Bay Way', 'nzZNgGbuVO', 'university                              ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('03 Springview Point', 'RcloEcttFB', 'community Center                        ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('132 Ramsey Hill', 'kFxdNhcvXL', 'Sports hall                             ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('4561 Melby Avenue', 'ObmQSwfzFi', 'community Center                        ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('4294 Larry Trail', 'yYKQSjEUpm', 'Nature site                             ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('57149 Summer Ridge Center', 'ltvvpJDtzN', 'Sports hall                             ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('3954 Columbus Road', 'EugdCZeFzX', 'hospital                                ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('931 Esker Center', 'wSHlSHtRnr', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('324 Haas Way', 'iITyeFGxjY', 'mall                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('66 Dexter Point', 'zLAgZBBzMC', 'clinic                                  ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('15539 Fulton Road', 'XiXcROxTii', 'hospital                                ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('33852 Onsgard Junction', 'rlrbjPAUKN', 'mall                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('104 John Wall Way', 'GIUWCYaTXm', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('73177 Morningstar Street', 'mOgwFOacDT', 'stadium                                 ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('93 Lakewood Crossing', 'SNXyXNpYkF', 'mall                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('91 Bellgrove Park', 'QNHXnDcJov', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('74061 International Alley', 'XDshlTIfPW', 'synagogue                               ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('703 Declaration Park', 'iXzNqpGxQM', 'bank                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('20041 6th Street', 'ErVArqfUKL', 'synagogue                               ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('55 Moulton Alley', 'kHuiALDuqD', 'clinic                                  ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('27 Magdeline Point', 'pQymjpfObz', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('827 Dwight Pass', 'VllYWAQfHN', 'bank                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('23053 Clemons Terrace', 'MdYODRjAqE', 'school                                  ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('61664 Kennedy Point', 'SbniOaxdXY', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('39469 Sage Avenue', 'ftdfhTilyI', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('57521 Melody Alley', 'NeYdgTOiQt', 'park                                    ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('898 Lotheville Center', 'MpbBlIbQjZ', 'hospital                                ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('424 Talmadge Point', 'ZgwJijzvHw', 'stadium                                 ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('96 Bartelt Point', 'VEnppHzJsm', 'stadium                                 ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('23 Moose Trail', 'XTMMMQZiyi', 'school                                  ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('41725 Steensland Road', 'hqNzXthWoG', 'stadium                                 ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('6003 Fallview Pass', 'hSnpQxkxEW', 'Sports hall                             ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('5104 Lakewood Parkway', 'DJjeZBydjJ', 'bank                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('7 Vidon Court', 'GOxBQGBcFL', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('0888 Westridge Way', 'cNvevgABoV', 'park                                    ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('3 Eastwood Lane', 'lgqKBhbncc', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('566 Forster Lane', 'yIsvyBxGCK', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('43 Loftsgordon Drive', 'gtbuAzggff', 'stadium                                 ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('6154 Magdeline Court', 'tfRVVyDUsV', 'Sports hall                             ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('7995 Sullivan Terrace', 'PHwGkDvsME', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('76 Gina Alley', 'TcxSBxchqs', 'visitors Center                         ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('4977 Cambridge Junction', 'zyRZmVYslA', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('22722 Northport Trail', 'xOXPyfOrST', 'hospital                                ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('471 Judy Pass', 'OzsUUbSdFJ', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('00 Monterey Center', 'GyRWdJpMGU', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('25 Linden Alley', 'NPdqwgoHug', 'stadium                                 ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('4337 Sundown Avenue', 'irufzpzqcz', 'university                              ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('720 Sloan Avenue', 'ikFDndbFLi', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('89 Jenna Court', 'NeYxPZqvVX', 'hospital                                ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('8 Loomis Plaza', 'qVsFBhveIq', 'visitors Center                         ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('1 Oak Street', 'AsRfkwyeXr', 'bank                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('5 Wayridge Point', 'XOkoqaTDaj', 'mall                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('503 Rowland Plaza', 'KygqTcyfaQ', 'school                                  ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('7 Monica Place', 'WUHYmTsXLH', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('4 Dwight Point', 'QLKubLiXpv', 'university                              ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('10 Sycamore Pass', 'KRwGWOJFVp', 'community Center                        ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('657 Hazelcrest Trail', 'qxGxfaTXVU', 'mall                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('7 Cambridge Street', 'gdZWhSAAww', 'museum                                  ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('9 Bluestem Point', 'dsFDErkxtW', 'school                                  ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('96 Schurz Parkway', 'WpbwgWcYiR', 'stadium                                 ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('44 Calypso Way', 'PzsCNUprtE', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('8 Moose Trail', 'BmPNNpRslR', 'school                                  ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('808 Superior Alley', 'blWeadwTxC', 'Sports hall                             ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('135 Weeping Birch Alley', 'TUYrtACnHA', 'stadium                                 ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('006 Jackson Point', 'ldLSkJXdBY', 'synagogue                               ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('66 Sheridan Place', 'eidyPRFJDr', 'park                                    ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('0 Fair Oaks Crossing', 'rWDrhEPrCB', 'stadium                                 ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('7409 Service Avenue', 'RHZdYDccWo', 'visitors Center                         ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('2745 Ruskin Junction', 'KNxlWSzEJL', 'hospital                                ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('43539 Main Trail', 'zrvtaLbJIb', 'mall                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('83 Iowa Crossing', 'zkPzKoyCtu', 'Nature site                             ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('21 Bellgrove Road', 'rTNZIgHzKY', 'community Center                        ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('66 Hazelcrest Plaza', 'ITLUZcOzYA', 'university                              ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('08330 Logan Trail', 'KlMIXZROUO', 'synagogue                               ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('8 Toban Court', 'RdmJbsMGRD', 'community Center                        ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('6 Transport Road', 'wnGHERTqqu', 'museum                                  ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('10 Shelley Terrace', 'PPVpEfUNcT', 'community Center                        ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('1 Debra Alley', 'XIPyosxWRq', 'synagogue                               ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('25716 Melvin Street', 'tYGAohvKlP', 'clinic                                  ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('568 Cardinal Drive', 'eNFoadustT', 'bank                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('29111 Esker Avenue', 'avEcSCiuIu', 'hospital                                ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('957 Mandrake Alley', 'WTMswvcNMu', 'school                                  ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('673 Caliangt Road', 'fAHhVfOmXd', 'Sports hall                             ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('6882 Coolidge Avenue', 'hRSTBaUTjF', 'Sports hall                             ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('71030 Monica Crossing', 'CVnivvcFBe', 'clinic                                  ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('8 Sachtjen Way', 'LDNgCyssiL', 'school                                  ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('8053 Northfield Way', 'zCgHwxXxcr', 'bank                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('87 Larry Hill', 'OkjYlvdlqK', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('419 Kingsford Alley', 'yNwTnFiffq', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('782 Meadow Ridge Alley', 'IlbDWUnHAf', 'museum                                  ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('45324 Sachs Way', 'nWxiUHMPQb', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('896 Columbus Court', 'xyDoXaQZMj', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('2 Kim Parkway', 'muHkdRGyDt', 'hospital                                ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('5 Mallard Street', 'fTKuSuNitc', 'clinic                                  ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('388 Green Lane', 'RixpBoUKRN', 'visitors Center                         ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('3 Fallview Junction', 'KIOUyHtVCQ', 'Sports hall                             ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('34 Maywood Point', 'OspprhKkty', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('34752 Esker Hill', 'jfRXsQkmEi', 'mall                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('881 Northfield Street', 'cbIZYYiuWU', 'Sports hall                             ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('06374 Iowa Avenue', 'WTyOlGllrV', 'community Center                        ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('127 Brickson Park Hill', 'kPSpoHEsKd', 'museum                                  ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('29 Schurz Park', 'CJJlTeqLAb', 'clinic                                  ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('0823 Susan Alley', 'JvyNmtlkao', 'stadium                                 ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('2702 Dakota Road', 'PollVHsAsr', 'school                                  ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('9 Elka Terrace', 'iWiVniBwvL', 'mall                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('7 Del Mar Plaza', 'HAahCrhyUG', 'Sports hall                             ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('7 Fordem Drive', 'aymGUQClqX', 'community Center                        ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('59 Hanson Junction', 'IKmOYLXhYX', 'Sports hall                             ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('96637 Towne Place', 'dVKWLreTXr', 'bank                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('54814 Prentice Alley', 'bZDYQLHWdJ', 'hospital                                ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('7207 Dakota Crossing', 'WqkXtprYYL', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('79042 Caliangt Court', 'hEhpFbpqYJ', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('1 Waywood Plaza', 'WyMTjPhjtu', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('3 Calypso Place', 'ChQEvFSidV', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('3 Sloan Crossing', 'cpzoxlMwyU', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('551 Everett Park', 'xQrmHnZGxt', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('525 Eliot Road', 'lclAOmazIc', 'park                                    ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('09482 Main Lane', 'lIZYYHZEbd', 'mall                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('97617 Sachtjen Alley', 'wwyPlCvWyD', 'park                                    ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('2096 Armistice Center', 'QniDVtZAtv', 'Nature site                             ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('14101 Texas Crossing', 'VTrErevBww', 'mall                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('098 West Terrace', 'kYoCPhFxNB', 'synagogue                               ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('0969 Schurz Center', 'iZQLBnJAIC', 'university                              ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('20 Muir Crossing', 'rBzJVrfpbM', 'hospital                                ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('03 Sullivan Plaza', 'TbQYNlECcn', 'university                              ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('2159 Loftsgordon Road', 'SFXYQxouEL', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('776 Springview Place', 'bGxOdUyUOu', 'synagogue                               ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('058 Pankratz Drive', 'WhaNoEMIbl', 'bank                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('5964 Truax Road', 'mAPFAuJpdH', 'Sports hall                             ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('4267 High Crossing Circle', 'aLwYsIRmCx', 'synagogue                               ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('832 Drewry Point', 'yjKREFDLhu', 'clinic                                  ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('59149 Raven Road', 'xLkOVWMXuy', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('08555 Glendale Pass', 'mGwpmbAbmT', 'park                                    ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('9 Pankratz Alley', 'VYWaLZyTQY', 'school                                  ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('70 Heath Street', 'JwtkQoKKFB', 'hospital                                ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('16 Westridge Circle', 'NhEYdLBsrr', 'school                                  ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('65786 Florence Plaza', 'IMDPtOFTbf', 'Sports hall                             ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('2173 Red Cloud Hill', 'eFRVpxrwGJ', 'Sports hall                             ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('2 East Terrace', 'DJKdxEwCwF', 'stadium                                 ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('7457 Charing Cross Court', 'kYGzTdlirW', 'community Center                        ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('11 Sunbrook Hill', 'ErRQRLKQQh', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('915 Duke Trail', 'huomwkjQsn', 'bank                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('4 Nelson Terrace', 'xMurUqVorT', 'museum                                  ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('9127 Dexter Circle', 'cLYKecziwN', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('98716 Dunning Hill', 'ZYEQASlkXF', 'clinic                                  ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('33 Division Avenue', 'LScmDWrtTh', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('76641 Forster Center', 'DpcLwPoRhC', 'Sports hall                             ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('34 Bultman Place', 'TLrqiZRuQN', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('91132 Everett Lane', 'APwRLRlIZE', 'university                              ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('39160 Cambridge Trail', 'mlrcnVzsxQ', 'school                                  ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('5518 Onsgard Center', 'yPqeHkILxE', 'museum                                  ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('93 Granby Way', 'ucaiThVxEF', 'Nature site                             ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('470 Bultman Junction', 'UnWqfprOAR', 'clinic                                  ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('31378 Union Avenue', 'HjWySvkEdm', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('63 Farragut Pass', 'KYsecCjozn', 'bank                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('92386 Di Loreto Road', 'mkRkqfougg', 'visitors Center                         ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('6965 Village Place', 'nrreCGsuBo', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('39021 Westridge Hill', 'lLbVCpTGiv', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('6345 Troy Road', 'TSyBEarmuT', 'community Center                        ', 'Community');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('78 Caliangt Center', 'fbPBTuCDUz', 'mall                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('279 American Ash Terrace', 'mtdcmNsfTw', 'hospital                                ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('38495 Eagle Crest Drive', 'uILdxDUorr', 'bank                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('05882 Lake View Lane', 'YqJMpHFnDX', 'bank                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('8565 Loftsgordon Avenue', 'tVQcRtffGP', 'Sports hall                             ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('59 Thierer Alley', 'NyBKzLsoBv', 'Nature site                             ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('2 Duke Way', 'XHFMNIqOgO', 'museum                                  ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('6029 Schlimgen Alley', 'zHpQzfavtu', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('083 Calypso Way', 'zvhWjuxTFN', 'Nature site                             ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('2793 Gateway Point', 'Wsczimolel', 'university                              ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('70 Merry Circle', 'wsXKNRvLbs', 'school                                  ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('30 Duke Center', 'QGpDIWplKb', 'university                              ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('49212 Schmedeman Terrace', 'EVHuFaPzHq', 'mall                                    ', 'Finance');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('246 Stang Street', 'dhJDSTchAQ', 'museum                                  ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('2 Texas Road', 'BKUhoTOGdS', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('523 High Crossing Parkway', 'wmtCKVRRgk', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('1171 Mesta Lane', 'oRjnPmNTRZ', 'Landfill                                ', 'Sanitation');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('12678 Division Parkway', 'eVecobRaMc', 'Sports hall                             ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('308 Hansons Hill', 'ecRMNuArzZ', 'university                              ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('755 Transport Alley', 'NoILghOXGP', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('149 Mccormick Terrace', 'jRZncvznxt', 'hospital                                ', 'Health');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('8 Southridge Crossing', 'JnOcmSmTEn', 'school                                  ', 'Education');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('013 Westridge Pass', 'SDLbLMGbqx', 'Nursing Home                            ', 'Welfare');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('416 Orin Crossing', 'cCwtpMBinQ', 'stadium                                 ', 'Sports');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('6211 Kipling Drive', 'oZSRvkQohJ', 'museum                                  ', 'Tourism');
INSERT INTO SYSTEM.INSTITUTION (ADDRESS, INSTNAME, TYPE, COMMITNAME) VALUES ('2 Hazelcrest Circle', 'eBErjoEQEU', 'Nursing Home                            ', 'Welfare');
