insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('71030 Monica Crossing','CVnivvcFBe','clinic','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('8 Sachtjen Way','LDNgCyssiL','School','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('8053 Northfield Way','zCgHwxXxcr','Bank','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('87 Larry Hill','OkjYlvdlqK','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('419 Kingsford Alley','yNwTnFiffq','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('782 Meadow Ridge Alley','IlbDWUnHAf','Museum','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('45324 Sachs Way','nWxiUHMPQb','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('896 Columbus Court','xyDoXaQZMj','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('2 Kim Parkway','muHkdRGyDt','Hospital','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('5 Mallard Street','fTKuSuNitc','clinic','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('388 Green Lane','RixpBoUKRN','Visitors center','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('3 Fallview Junction','KIOUyHtVCQ','Sports hall','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('34 Maywood Point','OspprhKkty','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('34752 Esker Hill','jfRXsQkmEi','Mall','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('881 Northfield Street','cbIZYYiuWU','Sports hall','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('73177 Morningstar Street','mOgwFOacDT','Stadium','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('93 Lakewood Crossing','SNXyXNpYkF','Mall','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('91 Bellgrove Park','QNHXnDcJov','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('74061 International Alley','XDshlTIfPW','Synagogue','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('703 Declaration Park','iXzNqpGxQM','Bank','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('20041 6th Street','ErVArqfUKL','Synagogue','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('55 Moulton Alley','kHuiALDuqD','clinic','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('27 Magdeline Point','pQymjpfObz','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('827 Dwight Pass','VllYWAQfHN','Bank','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('23053 Clemons Terrace','MdYODRjAqE','School','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('61664 Kennedy Point','SbniOaxdXY','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('39469 Sage Avenue','ftdfhTilyI','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('57521 Melody Alley','NeYdgTOiQt','Park','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('898 Lotheville Center','MpbBlIbQjZ','Hospital','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('424 Talmadge Point','ZgwJijzvHw','Stadium','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('96 Bartelt Point','VEnppHzJsm','Stadium','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('23 Moose Trail','XTMMMQZiyi','School','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('41725 Steensland Road','hqNzXthWoG','Stadium','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('6003 Fallview Pass','hSnpQxkxEW','Sports hall','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('5104 Lakewood Parkway','DJjeZBydjJ','Bank','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('7 Vidon Court','GOxBQGBcFL','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('0888 Westridge Way','cNvevgABoV','Park','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('3 Eastwood Lane','lgqKBhbncc','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('566 Forster Lane','yIsvyBxGCK','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('43 Loftsgordon Drive','gtbuAzggff','Stadium','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('6154 Magdeline Court','tfRVVyDUsV','Sports hall','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('7995 Sullivan Terrace','PHwGkDvsME','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('76 Gina Alley','TcxSBxchqs','Visitors center','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('4977 Cambridge Junction','zyRZmVYslA','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('22722 Northport Trail','xOXPyfOrST','Hospital','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('471 Judy Pass','OzsUUbSdFJ','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('00 Monterey Center','GyRWdJpMGU','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('25 Linden Alley','NPdqwgoHug','Stadium','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('4337 Sundown Avenue','irufzpzqcz','university','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('720 Sloan Avenue','ikFDndbFLi','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('89 Jenna Court','NeYxPZqvVX','Hospital','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('8 Loomis Plaza','qVsFBhveIq','Visitors center','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('1 Oak Street','AsRfkwyeXr','Bank','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('5 Wayridge Point','XOkoqaTDaj','Mall','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('503 Rowland Plaza','KygqTcyfaQ','School','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('7 Monica Place','WUHYmTsXLH','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('4 Dwight Point','QLKubLiXpv','university','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('10 Sycamore Pass','KRwGWOJFVp','Community center','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('657 Hazelcrest Trail','qxGxfaTXVU','Mall','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('7 Cambridge Street','gdZWhSAAww','Museum','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('9 Bluestem Point','dsFDErkxtW','School','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('96 Schurz Parkway','WpbwgWcYiR','Stadium','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('44 Calypso Way','PzsCNUprtE','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('8 Moose Trail','BmPNNpRslR','School','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('808 Superior Alley','blWeadwTxC','Sports hall','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('135 Weeping Birch Alley','TUYrtACnHA','Stadium','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('006 Jackson Point','ldLSkJXdBY','Synagogue','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('66 Sheridan Place','eidyPRFJDr','Park','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('0 Fair Oaks Crossing','rWDrhEPrCB','Stadium','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('7409 Service Avenue','RHZdYDccWo','Visitors center','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('2745 Ruskin Junction','KNxlWSzEJL','Hospital','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('43539 Main Trail','zrvtaLbJIb','Mall','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('83 Iowa Crossing','zkPzKoyCtu','Nature site','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('21 Bellgrove Road','rTNZIgHzKY','Community center','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('66 Hazelcrest Plaza','ITLUZcOzYA','university','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('08330 Logan Trail','KlMIXZROUO','Synagogue','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('8 Toban Court','RdmJbsMGRD','Community center','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('6 Transport Road','wnGHERTqqu','Museum','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('10 Shelley Terrace','PPVpEfUNcT','Community center','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('1 Debra Alley','XIPyosxWRq','Synagogue','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('25716 Melvin Street','tYGAohvKlP','clinic','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('568 Cardinal Drive','eNFoadustT','Bank','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('29111 Esker Avenue','avEcSCiuIu','Hospital','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('957 Mandrake Alley','WTMswvcNMu','School','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('673 Caliangt Road','fAHhVfOmXd','Sports hall','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('6882 Coolidge Avenue','hRSTBaUTjF','Sports hall','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('06374 Iowa Avenue','WTyOlGllrV','Community center','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('127 Brickson Park Hill','kPSpoHEsKd','Museum','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('29 Schurz Park','CJJlTeqLAb','clinic','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('0823 Susan Alley','JvyNmtlkao','Stadium','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('2702 Dakota Road','PollVHsAsr','School','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('9 Elka Terrace','iWiVniBwvL','Mall','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('7 Del Mar Plaza','HAahCrhyUG','Sports hall','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('7 Fordem Drive','aymGUQClqX','Community center','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('59 Hanson Junction','IKmOYLXhYX','Sports hall','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('96637 Towne Place','dVKWLreTXr','Bank','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('54814 Prentice Alley','bZDYQLHWdJ','Hospital','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('7207 Dakota Crossing','WqkXtprYYL','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('79042 Caliangt Court','hEhpFbpqYJ','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('1 Waywood Plaza','WyMTjPhjtu','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('3 Calypso Place','ChQEvFSidV','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('3 Sloan Crossing','cpzoxlMwyU','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('551 Everett Park','xQrmHnZGxt','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('525 Eliot Road','lclAOmazIc','Park','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('09482 Main Lane','lIZYYHZEbd','Mall','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('97617 Sachtjen Alley','wwyPlCvWyD','Park','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('2096 Armistice Center','QniDVtZAtv','Nature site','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('14101 Texas Crossing','VTrErevBww','Mall','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('098 West Terrace','kYoCPhFxNB','Synagogue','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('0969 Schurz Center','iZQLBnJAIC','university','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('20 Muir Crossing','rBzJVrfpbM','Hospital','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('03 Sullivan Plaza','TbQYNlECcn','university','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('2159 Loftsgordon Road','SFXYQxouEL','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('776 Springview Place','bGxOdUyUOu','Synagogue','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('058 Pankratz Drive','WhaNoEMIbl','Bank','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('5964 Truax Road','mAPFAuJpdH','Sports hall','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('4267 High Crossing Circle','aLwYsIRmCx','Synagogue','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('832 Drewry Point','yjKREFDLhu','clinic','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('59149 Raven Road','xLkOVWMXuy','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('08555 Glendale Pass','mGwpmbAbmT','Park','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('9 Pankratz Alley','VYWaLZyTQY','School','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('70 Heath Street','JwtkQoKKFB','Hospital','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('16 Westridge Circle','NhEYdLBsrr','School','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('65786 Florence Plaza','IMDPtOFTbf','Sports hall','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('2173 Red Cloud Hill','eFRVpxrwGJ','Sports hall','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('2 East Terrace','DJKdxEwCwF','Stadium','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('7457 Charing Cross Court','kYGzTdlirW','Community center','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('11 Sunbrook Hill','ErRQRLKQQh','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('915 Duke Trail','huomwkjQsn','Bank','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('4 Nelson Terrace','xMurUqVorT','Museum','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('9127 Dexter Circle','cLYKecziwN','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('98716 Dunning Hill','ZYEQASlkXF','clinic','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('33 Division Avenue','LScmDWrtTh','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('76641 Forster Center','DpcLwPoRhC','Sports hall','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('34 Bultman Place','TLrqiZRuQN','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('91132 Everett Lane','APwRLRlIZE','university','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('39160 Cambridge Trail','mlrcnVzsxQ','School','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('5518 Onsgard Center','yPqeHkILxE','Museum','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('93 Granby Way','ucaiThVxEF','Nature site','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('470 Bultman Junction','UnWqfprOAR','clinic','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('31378 Union Avenue','HjWySvkEdm','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('63 Farragut Pass','KYsecCjozn','Bank','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('92386 Di Loreto Road','mkRkqfougg','Visitors center','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('6965 Village Place','nrreCGsuBo','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('39021 Westridge Hill','lLbVCpTGiv','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('6345 Troy Road','TSyBEarmuT','Community center','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('78 Caliangt Center','fbPBTuCDUz','Mall','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('279 American Ash Terrace','mtdcmNsfTw','Hospital','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('38495 Eagle Crest Drive','uILdxDUorr','Bank','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('05882 Lake View Lane','YqJMpHFnDX','Bank','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('8565 Loftsgordon Avenue','tVQcRtffGP','Sports hall','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('59 Thierer Alley','NyBKzLsoBv','Nature site','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('2 Duke Way','XHFMNIqOgO','Museum','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('6029 Schlimgen Alley','zHpQzfavtu','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('083 Calypso Way','zvhWjuxTFN','Nature site','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('2793 Gateway Point','Wsczimolel','university','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('70 Merry Circle','wsXKNRvLbs','School','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('30 Duke Center','QGpDIWplKb','university','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('49212 Schmedeman Terrace','EVHuFaPzHq','Mall','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('246 Stang Street','dhJDSTchAQ','Museum','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('2 Texas Road','BKUhoTOGdS','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('523 High Crossing Parkway','wmtCKVRRgk','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('1171 Mesta Lane','oRjnPmNTRZ','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('12678 Division Parkway','eVecobRaMc','Sports hall','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('308 Hansons Hill','ecRMNuArzZ','university','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('755 Transport Alley','NoILghOXGP','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('149 Mccormick Terrace','jRZncvznxt','Hospital','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('8 Southridge Crossing','JnOcmSmTEn','School','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('013 Westridge Pass','SDLbLMGbqx','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('416 Orin Crossing','cCwtpMBinQ','Stadium','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('6211 Kipling Drive','oZSRvkQohJ','Museum','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('2 Hazelcrest Circle','eBErjoEQEU','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('9294 Arapahoe Center','ssZlddIGTl','clinic','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('70 Nancy Avenue','VZisvLBJrZ','Hospital','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('73 Packers Terrace','lgeucsjwws','Sports hall','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('5 Waywood Drive','RdIkDxWzjU','Bank','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('3374 Macpherson Center','yUmFPeOXIb','Park','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('4 David Junction','pUrEQskEci','Stadium','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('6509 Cardinal Alley','oTCOfIwRtu','university','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('343 Prairieview Place','UmbksrGVxA','Sports hall','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('33 Sachs Plaza','JBtNuthGSL','Sports hall','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('3 Upham Lane','yniInhyAwS','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('95 Mitchell Pass','vGdnaXfnhp','Mall','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('4565 Longview Alley','nvHcOYNwnG','Park','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('4855 Porter Point','CgZOtLkgVG','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('3 Mandrake Pass','UEcqsKhGGh','university','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('465 Forest Run Circle','MCacBTqcqC','Stadium','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('293 Pankratz Parkway','AVlxqPxJgn','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('0195 Crescent Oaks Street','HmqwnEMtQE','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('71 Killdeer Alley','HgaPRPWjUO','Museum','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('24 Weeping Birch Crossing','TajYWXKjfK','university','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('1 Glacier Hill Alley','QGjYLFCzcs','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('871 John Wall Trail','BbPIBxLYsR','School','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('0209 Division Plaza','yfqNRSdVBA','Park','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('5339 Kipling Drive','aiAvDJDDet','Bank','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('95751 Kingsford Lane','UXnhZjkYcl','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('18 Pine View Place','kMaUKVnPpt','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('616 Sheridan Trail','zTtSmAlqwP','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('31350 Judy Plaza','PXdqVsSblB','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('46 Moose Hill','GUBeyQnJgs','Mall','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('55 Fordem Trail','SZzvGsmvVU','university','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('85178 Corry Crossing','ioOSovqDwN','School','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('7 Merrick Trail','DaZAjiHKQO','School','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('9708 Evergreen Court','BltRobAxBL','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('485 Debs Junction','GhsUebwFfr','Park','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('9603 Westerfield Pass','NBRvRvjRdR','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('3 Merrick Parkway','uPUXvRHCWV','clinic','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('233 Acker Trail','DuxvKnflCM','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('163 Clove Park','CpqnEHcKkG','clinic','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('45 Brown Junction','NMpfVriDFd','Mall','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('48436 Chive Plaza','BSCMNilfCK','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('99 Vidon Court','SNcIILkbvL','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('74 Stone Corner Trail','oscsfvYRTK','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('43414 Merrick Center','xsLJsFXUNN','Hospital','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('91 Crownhardt Crossing','nXLKOVycVi','Park','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('20770 Shopko Park','kIDPKqBirY','Mall','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('55 Northview Avenue','AhDkHxhuTp','clinic','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('238 Russell Alley','bVkdMlfatG','Park','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('46568 Sutteridge Alley','fgbDUoZupF','Sports hall','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('98 Express Pass','pdjQKCdhhY','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('26 Barnett Drive','oNQNkuRiGQ','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('523 Meadow Ridge Street','kAfxSTrLGl','Nature site','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('411 Swallow Circle','SeUHHufpoe','clinic','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('6499 Prairie Rose Parkway','ShZObWVXVm','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('07 Lindbergh Circle','mDCIUKBCbJ','Visitors center','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('5525 Meadow Vale Road','oWXDfJJdzn','Sports hall','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('76317 Londonderry Point','jeOMWUGjdz','Stadium','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('8 Leroy Court','WpkXjDFIhe','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('6000 Golf Junction','VRDcvqEVtU','Mall','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('92 Ridgeview Hill','tMhZhkvXMw','Sports hall','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('6 Prairieview Lane','YIzorvLHiu','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('36267 2nd Terrace','WhTuunZevs','Stadium','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('903 North Crossing','GGlfrljDNs','Mall','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('1046 Ilene Court','DUyiSOqLyZ','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('6 Delladonna Park','FLHIxlzwSx','Bank','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('19 Carberry Avenue','UcDvEWJQMb','Museum','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('219 Bowman Plaza','KFezdNGGcr','Hospital','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('40816 Crest Line Junction','boDbVjRFHr','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('935 Manitowish Lane','cVBkqFrXTJ','university','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('59969 Sunfield Drive','UmErsjIwPJ','Museum','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('7 Dorton Center','wDyLIVUrWr','School','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('972 Northfield Trail','YKOvNATHEB','university','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('1777 Bonner Crossing','tZjCrJZylY','Bank','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('646 Meadow Valley Trail','RiSGtnUyka','Community center','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('0626 Warbler Hill','VqVrdTeBzA','Museum','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('60402 Superior Junction','YPdUhPLCYL','Sports hall','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('175 Dawn Terrace','pHtdURQSnI','Mall','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('8861 Crescent Oaks Hill','pCxUCdfWuD','Visitors center','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('0 Kropf Place','RzqqFmUOhu','Stadium','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('7 Muir Pass','wlzWEjCykE','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('55 Sunnyside Parkway','PyUxCupYVF','Synagogue','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('8923 Toban Point','wetKOhqXxw','Mall','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('3 Spaight Street','HCBMzxzySR','Community center','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('5 Lindbergh Street','VIYzWTdcAO','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('1946 Blackbird Park','UGLbJjjlsQ','Hospital','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('71 International Hill','PTvJZkXpkH','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('9048 Northridge Park','OsyWSMAEQH','School','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('8 Saint Paul Parkway','HkAGpYkYrw','Bank','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('2669 Melby Way','kUkpfXdeCI','Mall','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('34 Memorial Drive','dTsDxULeLx','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('3710 Elka Terrace','lhqIoVuXtm','Mall','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('536 6th Avenue','NDPOyktpAv','Mall','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('015 Anniversary Drive','LGmSjcbfKF','Nature site','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('4 Express Alley','cNgnbMHrgZ','Sports hall','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('55942 Gulseth Hill','BzlIpXBued','Bank','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('68 1st Center','JBFYhVnmqs','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('1502 Banding Road','WvBAaWgfJj','Park','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('8718 Hollow Ridge Park','LPLOouXQAH','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('3 Monument Point','QTsxuupQoR','Bank','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('20 Schmedeman Plaza','rxkEZsieYv','Museum','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('057 Mosinee Pass','naxsSSiQPf','School','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('0 Thierer Hill','XxPTuSsDxZ','university','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('15 Vernon Center','QwALSpqfwE','Park','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('59 Dakota Junction','rUtbLPGrbp','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('588 Kensington Place','rTopmLyQOW','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('947 Sage Circle','yadXRkhhGh','university','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('03146 Ludington Terrace','dAlZTqqllc','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('4778 Meadow Vale Drive','DxXFHRFZVo','Visitors center','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('6355 Basil Parkway','ZVfDGZhBIb','Mall','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('280 Loomis Lane','BNqqoWNmyC','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('82 Helena Alley','DWmPDLAQmV','Bank','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('8815 Anhalt Court','SGCRwbAZFK','School','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('84 Muir Pass','NDjpgesECH','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('6 Fisk Drive','ijopzukpmL','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('251 Spenser Drive','ffWgNIDewp','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('918 Monument Hill','ewdqIMDHAV','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('921 Porter Lane','xKeStQgPJL','School','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('308 Roth Center','kpYdUGmjfa','Visitors center','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('73259 Scofield Crossing','LMyLljArHT','clinic','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('789 Bunting Junction','rFtBEKxmcj','Hospital','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('0 Havey Park','CxyupRaMuS','Hospital','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('41 Novick Junction','IvyyDxfBOD','Mall','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('9164 Briar Crest Alley','gFtXpeyABi','Synagogue','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('12 Vahlen Plaza','kzaFfORthu','university','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('209 Vidon Park','EBCPvnBoYi','Hospital','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('59582 American Trail','phtYISddPB','Bank','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('81137 Morningstar Terrace','ilPSfmznXS','School','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('2543 Merchant Parkway','mVZvcYEtni','Community center','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('4 Starling Way','XuoHLdSGYk','clinic','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('395 Sauthoff Junction','zJLipzGhIv','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('74 Claremont Road','eQYMLjLQGA','Museum','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('4565 Sunfield Hill','QikERaXOBA','Visitors center','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('248 Lukken Drive','ufBlEHtipJ','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('72222 South Crossing','JOAiLMcwRR','Community center','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('7 Eggendart Street','GQGqbbDPNS','Mall','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('0 Blaine Place','IPwpAlvcEu','Sports hall','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('35 Huxley Lane','BbkrtjBjtL','School','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('651 Northport Crossing','FdzzPqETJY','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('8300 Village Green Court','KKAMdhPTxn','School','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('529 Old Shore Park','NfYfgdtODt','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('49 Old Shore Parkway','wVLASXrXWO','School','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('2525 Mandrake Circle','NnCCqugSbv','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('031 Surrey Lane','pmQaiunKLL','School','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('986 Morrow Hill','jUxNIFRKYU','Hospital','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('87496 Mesta Trail','rwZWGcktTB','Stadium','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('32 Anzinger Place','fqVBSwJfnm','Mall','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('2 Waxwing Road','YBtehabKOb','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('22174 Canary Point','baQmgYMEke','Mall','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('77907 Monterey Drive','NBcTEeblxO','Bank','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('6096 Bartelt Park','mVjeZRsvZX','clinic','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('50 Stone Corner Way','WSIUckcKfl','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('1837 Hazelcrest Point','urUKlgihLL','Visitors center','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('897 Goodland Center','fxyEUUnrXk','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('91459 Anniversary Pass','nVbnOwIHUn','School','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('988 Emmet Park','lrGUyvhHct','School','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('695 Derek Street','xVMmpQmAyX','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('9019 Brown Lane','fCORNWKIcr','Mall','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('023 Aberg Place','SvLJNRMBIW','Visitors center','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('7 Thackeray Trail','ekAuuAHnNA','Mall','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('430 Superior Road','lWBsKGZIWS','Bank','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('747 Cottonwood Street','edBoneWxpA','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('72 Donald Plaza','iENhNeoaVX','Hospital','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('7932 Dahle Park','NyXMrXhKxl','School','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('68576 7th Parkway','oIXsxhkjLn','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('8 Delaware Court','cNsjLLDTCl','Visitors center','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('95875 Center Street','FhHJnYrZCh','Mall','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('7877 Butterfield Court','qYXqPXafDN','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('207 Debra Alley','REikRMBBpr','Mall','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('35 Monica Crossing','tOmurkFaJf','Mall','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('23 Kropf Park','xdNhGZWlnl','Hospital','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('044 Tomscot Drive','wdFtLWLYOQ','university','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('7 Oriole Crossing','ClqYjLgsYa','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('8549 Kim Parkway','TnakYakXPZ','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('045 Randy Trail','QCeGuQEGQZ','Park','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('8 Dayton Center','kHqnhdrnBr','Bank','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('3432 Graceland Park','icLyElOKFs','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('517 Golden Leaf Trail','OJLvFecJdp','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('18743 Longview Alley','oFGxKmLXWf','Bank','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('6964 Cottonwood Place','daQMwxiooG','Museum','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('8873 Westend Circle','EGxjDUtZJj','university','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('7 Springview Drive','GdkWMYJlZm','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('90 Welch Park','iffdfMRJEU','School','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('540 Pepper Wood Road','FYvcqOuwru','Sports hall','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('2057 Hintze Road','zoRGIHLsQL','Bank','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('35 Pennsylvania Road','xzpVdjAGri','university','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('0 Messerschmidt Way','SeXtxvsehX','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('121 Birchwood Parkway','fMSykhIFYF','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('164 Bowman Park','BwnzWiwdsP','Stadium','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('2 Merry Trail','jyXyKWUQOn','School','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('79 Pepper Wood Avenue','aBhKJdTwdx','School','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('62 Sunnyside Plaza','WTbhUEebmo','Mall','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('2 Ruskin Park','virYQxySSt','Synagogue','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('785 Hallows Point','bZWODyJTuU','Sports hall','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('9245 Kedzie Hill','sbAjChFIun','Museum','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('15 4th Street','TRzjcQAwhl','Museum','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('457 Dayton Center','vRWipRqIMU','Museum','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('6 Mandrake Pass','wrcLxSCoev','Nature site','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('22 Towne Hill','kCeUlJhuaJ','Sports hall','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('44780 Ohio Avenue','hdzNCAtsLm','Sports hall','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('6580 Continental Parkway','rTDcYEMXoY','Mall','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('7092 Ruskin Point','dpagObNqtm','Community center','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('1 Ridgeway Drive','AjKdUBWupR','Museum','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('0875 Miller Terrace','DEcgOHYpWM','Sports hall','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('0248 Victoria Place','WKXnbscihb','Mall','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('811 Carberry Pass','MTZWdToyNN','Museum','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('30090 Springs Alley','mDgvCpJJSy','clinic','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('17 Coolidge Hill','PeIoAmdMEH','Park','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('8197 Ryan Hill','BJBWaDDWgA','Community center','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('5 Lyons Alley','lzrkbleedM','Mall','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('5 Barby Lane','OLmhxBvTRG','university','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('963 Karstens Drive','GOCxQXCRpp','School','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('2 Graceland Circle','ijmDcPUgcb','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('3 Pennsylvania Plaza','vJmEOircvB','School','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('08 Karstens Terrace','FOQYeOVRsf','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('3 Bonner Parkway','GYvVExXQPA','Hospital','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('5581 Texas Center','HeKCxHJKCq','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('6 Morning Lane','IlokMkeLiQ','School','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('5 Lukken Hill','KartLrAbdT','Visitors center','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('83 John Wall Way','VYIQdlneKA','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('13892 Corben Road','NKzBJIkeuf','Sports hall','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('9491 Hermina Crossing','fuIRzNHWtm','Bank','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('25611 Lunder Circle','YUcmLedVZH','Synagogue','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('426 7th Park','SwYydiAtWc','Synagogue','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('74269 Goodland Crossing','nGokUkqUGT','clinic','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('32 Melrose Place','Gwmrkfpldk','clinic','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('8453 Pepper Wood Court','dBpVqssiJv','university','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('1 Utah Crossing','LTLZnwrDGn','university','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('78388 David Lane','PgHmMFJKBQ','School','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('6 Continental Plaza','kkQjruBEAz','Sports hall','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('12969 Division Court','FcKVtrmUjX','School','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('000 Cardinal Place','DkiKTARkKn','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('95747 Charing Cross Lane','YIJxRlnJsT','university','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('252 Talisman Street','VqAiSmPvFX','Synagogue','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('949 Brickson Park Drive','pSWMtFvuff','Community center','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('70558 Sage Court','lQuJDFElUa','Community center','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('533 South Place','RaOyqEAEgV','clinic','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('226 Darwin Park','vXDaPzYWSU','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('803 Nelson Way','ywjTMoBZia','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('8 Almo Circle','qqaHppgEBg','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('3 Bunting Lane','SShIUeVeBK','Park','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('425 Calypso Terrace','BKQbIjFesI','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('174 Meadow Valley Street','hImRFFsuOM','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('17 Burning Wood Street','rzUkKQAJOk','Sports hall','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('22107 Menomonie Circle','JdzSLLYDKP','clinic','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('065 Surrey Terrace','AmMdpPcSjI','Sports hall','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('4 Heath Place','dmafcEGcEv','university','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('85986 Myrtle Lane','rxrDCgxGzI','Synagogue','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('23 Mesta Junction','MtniiyrLJF','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('2090 Menomonie Court','DaKIdtEbLl','Mall','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('8 Ruskin Junction','ExLaZRNZim','Synagogue','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('70 Gale Point','aHMvNRycHn','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('0057 Dryden Plaza','axTJhTwMqA','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('04 Goodland Junction','EPhOLvIyEy','Museum','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('54337 Crowley Alley','XreZgzjuzK','university','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('140 Thackeray Lane','IYKNAFCZTx','Stadium','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('065 Artisan Park','rNggMauAbh','Bank','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('2 Springview Plaza','PlROomFtAp','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('672 Del Mar Street','vHbJoKouBS','Visitors center','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('4942 Waywood Avenue','WBSCaLMZVj','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('04 Stone Corner Terrace','PvBRZOCOMc','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('88 Columbus Plaza','wXKmOWSgJD','Community center','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('4 Comanche Circle','nigWREjcXQ','Nature site','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('0074 Bayside Circle','JFkfnkDGcm','clinic','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('7585 Judy Place','sWkigoOhBY','clinic','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('761 Hooker Point','gjoNTIXvnQ','Stadium','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('84372 Express Plaza','oGZeYrqYYh','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('33 Arkansas Circle','CNtetHkdRy','Mall','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('2197 Farwell Trail','ULyAlVddYj','Mall','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('1 Carioca Crossing','EdATUgEFaW','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('52 Barnett Park','jzNPeJDopF','Bank','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('552 Northwestern Park','wMRYaTctrQ','university','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('1155 Dottie Park','BQxDWBewJG','Mall','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('4 Jay Plaza','GTCkdXCqbv','Nature site','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('2815 Miller Parkway','qgQScfMxvO','Community center','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('2986 Basil Pass','UqQTvyAkGJ','Mall','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('084 Hudson Court','kgCOemXguw','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('0074 Talmadge Trail','zLwEDwmaBZ','Bank','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('95796 Acker Lane','xqmDqLaqGU','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('6 Thierer Lane','HkdGtOWSxf','Mall','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('2332 Jay Court','TjMxbEzUIW','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('51444 Eggendart Avenue','aZVmmXhfVc','Hospital','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('58 Arapahoe Road','fXyGhdZzVD','Visitors center','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('83797 Truax Court','htPfWuNhBp','Stadium','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('7 Warrior Park','BQedlkWpwd','Community center','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('73066 Autumn Leaf Trail','PnhmZENAGv','School','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('3 Cardinal Place','qtcVQuuFDr','Sports hall','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('11965 Holy Cross Point','fXMkYcjcle','Stadium','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('61 Cascade Terrace','XSUFlhdgVv','Community center','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('7 Sullivan Crossing','knCWnkEFfX','Mall','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('237 Carberry Lane','jpBlNlgVlM','Stadium','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('166 Shasta Parkway','pcxaZBmbkq','Hospital','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('4 Sunnyside Road','WBFyEBYUBu','Visitors center','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('3 Novick Street','IcDmBBSHED','Hospital','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('468 Clyde Gallagher Pass','guXoVsUaCJ','School','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('6404 Russell Hill','PYFJJrYyzk','clinic','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('8 Scofield Parkway','FNkWuCOfZj','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('26705 Scofield Street','FUzOZRqLSb','university','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('8 Harper Parkway','OLPEaGvaLp','Mall','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('79070 Lerdahl Avenue','XdQKYbSwHT','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('4 Northfield Park','LKjjmxLDty','Mall','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('180 Thompson Park','kWuhaZguGW','Nature site','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('676 Sloan Point','zZhNoFDLUs','Synagogue','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('667 7th Lane','ywfGNGTvrV','Stadium','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('53 Barnett Lane','WQnFHaDnim','Museum','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('26553 Sage Parkway','XkxGgubObw','Hospital','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('168 Evergreen Way','wSGHWOQvGQ','university','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('77 Village Green Trail','hGyyLDLnvk','Community center','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('7920 Derek Lane','fAeYtnEBxl','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('6 Mallard Junction','zASJxqJXGC','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('28436 Forest Run Pass','buhLWYQTgv','clinic','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('4868 Sunnyside Court','qatEXXGhrG','Park','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('0 Straubel Place','WmfAjKbUSe','Landfill','Sanitation');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('2 Holy Cross Drive','IKKheAXLAh','School','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('0788 Arizona Lane','OTDEkWqlSt','Bank','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('0430 Drewry Center','TtCDuqMwcO','Community center','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('839 Forster Terrace','NtdqXFOuXq','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('06358 Summit Circle','IOLHnHMJzl','Sports hall','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('7326 Bay Way','nzZNgGbuVO','university','Education');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('03 Springview Point','RcloEcttFB','Community center','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('132 Ramsey Hill','kFxdNhcvXL','Sports hall','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('4561 Melby Avenue','ObmQSwfzFi','Community center','Community');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('4294 Larry Trail','yYKQSjEUpm','Nature site','Tourism');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('57149 Summer Ridge Center','ltvvpJDtzN','Sports hall','Sports');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('3954 Columbus Road','EugdCZeFzX','Hospital','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('931 Esker Center','wSHlSHtRnr','Nursing Home','Welfare');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('324 Haas Way','iITyeFGxjY','Mall','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('66 Dexter Point','zLAgZBBzMC','clinic','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('15539 Fulton Road','XiXcROxTii','Hospital','Health');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('33852 Onsgard Junction','rlrbjPAUKN','Mall','Finance');
insert into SYSTEM.INSTITUTION(address,instname,type,commitname) values ('104 John Wall Way','GIUWCYaTXm','Nursing Home','Welfare');
commit;